MODEL:
  NAME: "siggraph"
  DOWNLOAD_PRETRAINED: True
DATASETS:
  TRAIN: ("landscape_train",)
  TEST: ("landscape_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 2
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  MAX_ITER: 100000
  IMS_PER_BATCH: 5
  CHECKPOINT_PERIOD_EPOCH: 1
  CHECKPOINT_PERIOD: 200000
  MAX_ITER_EPOCH: 1
  TEST_PERIOD: -1
INPUT:
  BRIGHTNESS: 0.3
  CONTRAST: 0.3
  SATURATION: 0.3
  HUE: 0.3
  MAX_SIZE_TRAIN: 256
  CROPPING: False
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 256
  COLOR_SPACE: 'LAB'
TEST:
  IMS_PER_BATCH: 1
  SAVE_SAMPLE_IMGS: True


